### ISSUE TITLE
Duplicate !doctype and head

### ISSUE THREAD

**Issue by edent** [railsgirls/railsgirls.com#2237]
The [homepage](https://railsgirls.com/) has this weird HTML error. Looks like something is putting the `!doctype` and part of `<head>` in twice.

![Source code view](https://github.com/user-attachments/assets/c23aaf53-1de1-4736-ad26-52a184b2de37)

**Comment by vesan** [comment]
Thanks for reporting! Fixed in https://github.com/railsgirls/railsgirls.com/commit/45b59ba0de839c301a2c824d5e8a96fe1e55e319
